#!/bin/bash

# remove old version of the autogenerated files
rm proto/echo-service_grpc.pb.go || true
rm proto/echo-service.pb.go || true
rm proto/echo-service.pb.gw.go || true

# Generate protobuf and grpc service
protoc --go_out=. --go_opt=paths=source_relative proto/echo-service.proto
protoc --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/echo-service.proto

# Generate REST proxy
protoc --grpc-gateway_out=. --grpc-gateway_opt=paths=source_relative proto/echo-service.proto

# Generate swagger file
protoc --openapiv2_out=. proto/echo-service.proto